config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'parking_spaces/search' => 'parking_spaces#search'
  get 'parking_spaces/bookings' => 'parking_spaces#bookings'
    
  resources :parking_spaces do
    resources :bookings
  end
    
  resources :charges

  devise_for :users
end

app/models/parking_space.rb
class ParkingSpace < ApplicationRecord
    belongs_to :user
    has_many :bookings, dependent: :destroy
    validates :name, :address, :cost, :user_id, presence: true
end

app/controllers/parking_spaces_controller.rb
class ParkingSpacesController < ApplicationController
  before_action :authenticated_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @parking_spaces = ParkingSpace.all
  end

  def search
    if params[:search].blank?
      @search_term = 'N/A'
      @results = ParkingSpace.all
    else
      @search_term = params[:search]
      @parameter = params[:search].downcase
      @results = ParkingSpace.all.where("lower(name) LIKE :search OR lower(address) LIKE :search OR lower(description) LIKE :search", search: "%#{@parameter}%")
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
      @parking_space = ParkingSpace.find(params[:id])
  end

  # GET /posts/new
  def new
    @parking_space = current_user.parking_space.new
  end

  # GET /posts/1/edit
  def edit
      @parking_space = ParkingSpace.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @parking_space = current_user.parking_space.new(post_params)

    respond_to do |format|
      if @parking_space.save
        format.html { redirect_to @parking_space, notice: 'Parking space was successfully listed.' }
        format.json { render :show, status: :created, location: @parking_space }
      else
        format.html { render :new }
        format.json { render json: @parking_space.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Parking space was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Parking space was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = ParkingSpace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:parking_space).permit(:name, :description, :address, :cost)
    end
end

app/views/parking_spaces/_form.html.erb
<%= form_with(model: @parking_space, local: true) do |form| %>
  <% if @parking_space.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking_space.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @parking_space.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :cost, 'Price/hr (€)' %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parking_spaces/book.html.erb
<h1>Checkout</h1>
<%- form_tag charges_path do %>
<article>
  <% if flash[:error].present? %>
    <div id='error_explanation'>
      <p><%= flash[:error] %></p>
    </div>
  <% end %>
  <label class='amount'>
    <span>Amount: €<%= @order.price %></span>  
  </label>
</article>

<script scr="https://checkout.stripe.come/checkout.js" class="stripe-button" data-key='<%= Rails.configuration.stripe[:publishable_key] %>' data-description="Space's price for allotted time" data-amount='<%= @order.price %>' data-locale='auto'></script>
<% end %>

app/views/parking_spaces/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', parking_space: @parking_space %>

<%= link_to 'Show', @parking_space %> |
<%= link_to 'Delete', @parking_space, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', parking_space_path %>

app/views/parking_spaces/index.html.erb
<h1>Parking Spaces</h1>

<table style="table-layout: fixed; width: 100%;">
  <thead align="left">
    <tr>
      <th>Posted by</th>
      <th>Title</th>
      <th>Address</th>
      <th>Price/hr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parking_spaces.each do |parking_space| %>
      <tr>
        <td><%= User.find(parking_space.user_id).username %></td>
        <td><%= parking_space.name %></td>
        <td><%= parking_space.address %></td>
        <td>€<%= parking_space.cost %></td>
        <td><%= link_to 'Details', parking_space %></td>
        <% if current_user.id == parking_space.user_id %>
          <td><%= link_to 'Edit', edit_parking_space_path(parking_space) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Parking Space', new_parking_space_path %>

app/views/parking_spaces/new.html.erb
<h1>New Parking Space</h1>

<%= render 'form', parking_space: @parking_space %>

<%= link_to 'Cancel', :back %>

app/views/parking_spaces/search.html.erb
<h1>Search</h1>

<p>Searching for: <%= @search_term %></p>

<table style="table-layout: fixed; width: 100%;">
  <thead align="left">
    <tr>
      <th>Posted by</th>
      <th>Title</th>
      <th>Address</th>
      <th>Price/hr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @results.each do |result| %>  
  <tbody>
    <tr>
      <td><%= User.find(result.user_id).username %></td>
      <td><%= result.name %></td>
      <td><%= result.address %></td>
      <td>€<%= result.cost %></td>
      <td><%= link_to 'Details', result %></td>
      <% if current_user.id == result.user_id %>
          <td><%= link_to 'Edit', edit_parking_space_path(result) %></td>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</table>

app/views/parking_spaces/show.html.erb
<div id="container">
  <div id="first" style="width: 35%">
    <h1>Details</h1>
    <p>
      <strong>Name:</strong>
      <%= @parking_space.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @parking_space.address %>
    </p>

    <p>
      <strong>Price/hr:</strong>
      €<%= @parking_space.cost %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @parking_space.description %>
    </p>

    <% if current_user.id == @parking_space.user_id %>
      <%= link_to 'Edit', edit_parking_space_path(id: @parking_space.id) %> |
    <%= link_to 'Bookings', parking_space_bookings_path(@parking_space.id) %> | 
    <% end %>
    <%= link_to 'Back', parking_spaces_path %>
  </div>
    
  <div id="second" style="float: left">
      <h1>Make Booking</h1>
      <%= link_to '<button type="button">Book</button>'.html_safe, new_parking_space_booking_path(@parking_space.id) %>
  </div>
  
</div>