config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'parking_spaces/search' => 'parking_spaces#search'
  get 'parking_spaces/bookings' => 'parking_spaces#bookings'
    
  resources :parking_spaces do
    resources :bookings
  end
    
  resources :charges

  devise_for :users
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :parking_space
    belongs_to :user
    validates :start_time, :end_time, :price, :parking_space_id, :user_id, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticated_user!
  before_action :set_parking_space

  def index
    @parking_space_id = params[:parking_space_id]
    @bookings = Booking.where(:parking_space_id => params[:parking_space_id])
  end

  # GET /bookings/new
  def new
    @booking = @parking_space.bookings.new
  end

  # GET /posts/1/edit
  def edit
  end
  # POST /posts
  # POST /posts.json
  def create  
    @start_time = DateTime.parse(params["booking"]["start_time(1i)"].to_s + '-' + params["booking"]["start_time(2i)"].to_s + '-' + params["booking"]["start_time(3i)"].to_s + ' ' + params["booking"]["start_time(4i)"].to_s + ':' + params["booking"]["start_time(5i)"].to_s + ':' + '0')
      
    @end_time = DateTime.parse(params["booking"]["end_time(1i)"].to_s + '-' + params["booking"]["end_time(2i)"].to_s + '-' + params["booking"]["end_time(3i)"].to_s + ' ' + params["booking"]["end_time(4i)"].to_s + ':' + params["booking"]["end_time(5i)"].to_s + ':' + '0')
        
    @booking = Booking.new(:price => params[:hiddenPrice], :parking_space_id => params[:parking_space_id], :user_id => current_user.id, :start_time => @start_time, :end_time => @end_time)
      
    @booking.save

    redirect_to new_charge_path(booking: @booking, price: params[:hiddenPrice])
    # after saving redirect to charges controller to make the charge. Example of how to link to a route with nested resources:
    # redirect_to parking_space_booking_path(@parking_space, @booking)
  end

  def destroy
    @booking = Booking.where(:id => params[:id], :parking_space_id => params[:parking_space_id]).first
    @booking.delete
    respond_to do |format|
      format.html { redirect_to parking_spaces_url, notice: 'Booking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_space
      @parking_space = ParkingSpace.find(params[:parking_space_id])
    end

    def set_booking
      @booking = Booking.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def booking_params
      params.require(:booking).permit(:start_time, :end_time, :price, :parking_space_id, :user_id)
    end
end

app/views/bookings/_form.html.erb
<%= form_for [@parking_space, @booking] do %>

  <div id="second" style="float: left">
    <h1>Book</h1>

    <label>Start Time: </label>
    <%= time_select :booking, :start_time %>
    <br><%= date_select :booking, :start_time %>
      
    <br><br><label>End Time: </label>
    <%= time_select :booking, :end_time%>
    <br><%= date_select :booking, :end_time%>
      
      <br><br>
      <p><strong>Total Price: </strong><u id="totalPrice">Select a Time</u></p>
      <%= hidden_field_tag(:hiddenPrice) %>
      <%= hidden_field_tag(:parking_space_id, value=@parking_space.id) %>

      <div class="input-group">
        <%= submit_tag "Book" %>
      </div>
  </div>

<% end %>

<script>
function defaultValues() {
    var d = new Date();

    document.getElementById("booking_start_time_4i").value = d.getHours();
    document.getElementById("booking_start_time_5i").value = d.getMinutes();
    document.getElementById("booking_start_time_1i").value = d.getYear();
    document.getElementById("booking_start_time_2i").value = d.getMonth();
    document.getElementById("booking_start_time_3i").value = d.getDay();
    
    document.getElementById("booking_end_time_4i").value = d.getHours() + 1;
    document.getElementById("booking_end_time_5i").value = d.getMinutes();
    document.getElementById("booking_end_time_1i").value = d.getYear();
    document.getElementById("booking_end_time_2i").value = d.getMonth();
    document.getElementById("booking_end_time_3i").value = d.getDay();
    
    document.getElementById("booking_start_time_4i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_start_time_5i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_start_time_1i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_start_time_2i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_start_time_3i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    
    document.getElementById("booking_end_time_4i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_end_time_5i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_end_time_1i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_end_time_2i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
    document.getElementById("booking_end_time_3i").setAttribute("onchange", function(){getPrice(<%= @parking_space.cost %>);}())
}

function getPrice(price) {
    console.log("getting price");
    
    var t1 = new Date(document.getElementById("booking_start_time_2i").value + ' ' + document.getElementById("booking_start_time_3i").value + ", " + document.getElementById("booking_start_time_1i").value + " " + document.getElementById("booking_start_time_4i").value + ":" + document.getElementById("booking_start_time_3i").value + ":00");
    
    var t2 = new Date(document.getElementById("booking_end_time_2i").value + ' ' + document.getElementById("booking_end_time_3i").value + ", " + document.getElementById("booking_end_time_1i").value + " " + document.getElementById("booking_end_time_4i").value + ":" + document.getElementById("booking_end_time_3i").value + ":00");

    var millis = t2 - t1

    var minutes = Math.floor((millis / (1000*60)) % 60);
    var hours   = Math.floor((millis / (1000*60*60)) % 24);

    totalPrice = ((price * hours) + (price * (minutes / 60))).toFixed(2);
    if (totalPrice == 'NaN' || totalPrice < 0) {
        totalPrice = "Invalid Times";
    }
    else {
        totalPrice = '€' + totalPrice;
    }

    document.getElementById("totalPrice").innerHTML = totalPrice;
    document.getElementById("hiddenPrice").value = totalPrice.substring(1);
}



document.addEventListener("turbolinks:load", function() {
  defaultValues();
  getPrice(<%= @parking_space.cost %>);
})
</script>

app/views/bookings/index.html.erb
<!-- TODO move this code over to bookings index -->

<h1>Bookings</h1>

<table style="table-layout: fixed; width: 100%;">
  <thead align="left">
    <tr>
      <th>Parking Space</th>
      <th>User</th>
      <th>Time</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <% @bookings.each do |result| %>
  <tbody>
    <tr>
      <td><%= link_to result.parking_space_id, parking_space_url(result.parking_space_id) %></td>
      <td><%= User.where(:id => result.user_id).first.username %></td>
      <td><%= result.start_time %> - <%= result.end_time %></td>
      <td>€<%= result.price %></td>
      <% if current_user.id == result.user_id %>
        <td><%= link_to 'Delete', parking_space_booking_path(:id => result.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
  </tbody>
  <% end %>
</table>

<%= link_to "Back", parking_space_url(@parking_space_id) %>

app/views/bookings/new.html.erb
  <div id="first" style="width: 35%">
    <h1>Details</h1>
    <p>
      <strong>Name:</strong>
      <%= @parking_space.name %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @parking_space.address %>
    </p>

    <p>
      <strong>Price/hr:</strong>
      €<%= @parking_space.cost %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @parking_space.description %>
    </p>

    <%= link_to 'Cancel', parking_space_path(@parking_space.id) %>
  </div>

   <%= render 'form', booking: @booking %>

app/views/bookings/show.html.erb
<h1>Booking</h1>