config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  get 'parking_spaces/search' => 'parking_spaces#search'
  get 'parking_spaces/bookings' => 'parking_spaces#bookings'
    
  resources :parking_spaces do
    resources :bookings
  end
    
  resources :charges

  devise_for :users
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticated_user!
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end
    
  def search
    if params[:search].blank?  
      @search_term = 'N/A'
      @results = Post.all  
    else  
      @search_term = params[:search]
      @parameter = params[:search].downcase  
      @results = Post.all.where("lower(title) LIKE :search OR lower(address) LIKE :search OR lower(body) LIKE :search OR lower(posted_by) LIKE :search", search: "%#{@parameter}%")
    end
  end
    
  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end
    
  def book
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.posted_by = current_user.username
    @post.email = current_user.email

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :address, :cost)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :cost, 'Price/hr (€)' %>
    <%= form.text_field :cost %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Delete', @post, method: :delete, data: { confirm: 'Are you sure?' } %> | 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Posted by</th>
      <th>Title</th>
      <th>Address</th>
      <th>Price/hr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.posted_by %></td>
        <td><%= post.title %></td>
        <td><%= post.address %></td>
        <td>€<%= post.cost %></td>
        <td><%= link_to 'Details', post %></td>
        <% if current_user.email == post.email %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Cancel', posts_path %>

app/views/posts/show.html.erb
<div id="container">
  <div id="first" style="width: 35%">
    <h1>Details</h1>
    <p>
      <strong>Posted by:</strong>
      <%= @post.posted_by %>
    </p>
    <p>
      <strong>Name:</strong>
      <%= @post.title %>
    </p>

    <p>
      <strong>Address:</strong>
      <%= @post.address %>
    </p>

    <p>
      <strong>Price/hr:</strong>
      €<%= @post.cost %>
    </p>

    <p>
      <strong>Description:</strong>
      <%= @post.body %>
    </p>

    <% if current_user.email == @post.email %>
      <%= link_to 'Edit', edit_post_path(@post) %> |
    <% end %>
    <%= link_to 'Back', :back %>
  </div>
    
  <div id="second" style="float: left">
    <h1>Book</h1>
    <label>Start Time: </label>
    <input id="time1" type="time" onChange="getPrice(<%= @post.cost %>)"/>
    <input id="time2" type="date" onChange="getPrice(<%= @post.cost %>)"/>
    <br><br>
    <label>End Time: </label>
    <input id="time3" type="time" onChange="getPrice(<%= @post.cost %>)"/>
    <input id="time4" type="date" onChange="getPrice(<%= @post.cost %>)"/>
    
    <%= form_tag(new_charge_path, :method => "get") do %>
      <p><strong>Total Price: </strong><u id="totalPrice">Select a Time</u></p>
      <%= hidden_field_tag(:hiddenPrice) %>
      <%= hidden_field_tag('post', @post) %>
      
      <div class="input-group">  
        <%= button_tag "Book" %>   
      </div>
    <% end %>
  </div>
</div>

<script>
function defaultValues() {
    var d = new Date();
    var day = d.getDate();
    var m = d.getMonth() + 1
    if (m < 10) {
        m = '0' + m;
    }
    if (day < 10) {
        day = '0' + day;
    }
    today = d.getFullYear() + '-' + m + '-' + day;
    var h = d.getHours();
    var mi = d.getMinutes();
    if (h < 10) {
        h = '0' + h;
    }
    if (mi < 10) {
        mi = '0' + mi;
    }
    now = h + ":" + mi;
    later = (parseInt(h) + 1) + ":" + mi;
    if (later.length < 5) {
        later = '0' + later;
    }
    
    document.getElementById("time2").value = today;
    document.getElementById("time4").value = today;
    document.getElementById("time1").value = now;
    document.getElementById("time3").value = later;
}
    
function getPrice(price) {  
    var t1 = new Date(document.getElementById("time2").value + ' ' + document.getElementById("time1").value);
        
    var t2 = new Date(document.getElementById("time4").value + ' ' + document.getElementById("time3").value);
    
    var millis = t2 - t1
     
    var minutes = Math.floor((millis / (1000*60)) % 60);
    var hours   = Math.floor((millis / (1000*60*60)) % 24);
    
    totalPrice = ((price * hours) + (price * (minutes / 60))).toFixed(2);
    if (totalPrice == 'NaN' || totalPrice < 0) {
        totalPrice = "Invalid Times";
    }
    else {
        totalPrice = '€' + totalPrice;
    }
        
    document.getElementById("totalPrice").innerHTML = totalPrice;
    document.getElementById("hiddenPrice").value = totalPrice.substring(1);
}
    


document.addEventListener("turbolinks:load", function() {
  defaultValues();
  getPrice(<%= @post.cost %>);
})
</script>